#pragma once
#define DEBUG_USE_SIMON_TEST_KEY_CONTROL
#define DEBUG_ENABLE_SET_STAGE_BLOCK_KEY_CONTROL
//#define DEBUG_SHOW_LOG_WHEN_SIMON_CONTACT_ENEMY
//#define DEBUG_SHOW_LOG_WHEN_ENEMY_CONTACT_SIMON
//#define DEBUG_SHOW_LOG_WHEN_WEAPON_CONTACT_ENEMY
//#define DEBUG_SHOW_LOG_WHEN_WEAPON_CONTACT_SIMON
//#define DEBUG_SHOW_LOG_WHEN_ENEMY_SKILL_CONTACT_SIMON

#define DEBUG_ENEMY_NOT_HURT_SIMON_WHEN_CONTACT
#define DEBUG_ENEMY_SKILL_NOT_HURT_SIMON_WHEN_CONTACT
//#define DEBUG_WHIP_NOT_HURT_ENEMY_WHEN_CONTACT
//#define DEBUG_SUBWEAPON_NOT_HURT_ENEMY_WHEN_CONTACT

#define SAFE_BREAK_BEGIN for(int x7dawx = 0; x7dawx < 1; x7dawx++){
#define SAFE_BREAK_END }
#define SAFE_BREAK break;