#pragma once
#define DEBUG_CONTACT_WITH_ENEMY
#define DEBUG_SIMON_KEY_CONTROL
//#define DEBUG_CONTACT_WITH_SIMON
#define DEBUG_WEAPON_CONTACT_WITH_ENEMY
#define DEBUG_WEAPON_CONTACT_WITH_SIMON
//#define DEBUG_AI_SKILL_CONTACT_WITH_SIMON
